### PR TITLE
V.5.x

### PR DESCRIPTION
**Pull request by klas**
Compatibility with Oro Platform 5.0 and later

### CODE REVIEW

**Comment by chrisaligent** [comment]
Hi @klas , thanks for working on this! We were going to need this soon too for a few client sites upgrading to 5.0.X.

The only concern I have is that we can't yet guarantee that this will work in 5.1.X, so we might need to be more strict about our version constraints for now.

ie:
```json
    "require": {
        "oro/platform": "5.*",
```
might need to be:
```json
    "require": {
        "oro/platform": "5.0.*",
```

I'm happy with the other changes though, they look good. And thanks for updating the Readme :+1:

**Comment by klas** [comment]
Hi @chrisaligent , chaged as requested to a stricter Oro Platform version

**Review by AdamJHall — APPROVED** [review]
Looks good to me :)

**Review by chrisaligent — APPROVED** [review]

**Comment by chrisaligent** [comment]
Merged into `master` and new `v5.0.x` branch, tagged as new `v5.0.0` release:
https://github.com/FriendsOfOro/OroRecaptchaBundle/releases/tag/v5.0.0

Confirmed also available on Packagist now:
https://packagist.org/packages/friendsoforo/oro-recaptcha-bundle

**Pull request merged**
